Add latest link, past deployment list & ?date=latest support
base-cms/base-cms pull request #497
Opened 2020-11-18 21:58 UTC by B77Mills

- Add campaigns to newsletter nodes on mapping of templates by alias
 - update admin to display [ Latest] [ Todays ] [ Select Date ] when campaigns are set
 - added scrollable Past Deployment: list when campaigns are set
 - adjusted no templates for alias text
 - minor look and feel adjustments to layouts on admin list of Newsletters
 - update template route to account for ?date=latest
 -- when a campaign is returned it will update the date to be the last deployed campaign date or return and invalid date error

![Screen Shot 2020-11-18 at 3 48 11 PM](https://user-images.githubusercontent.com/3845869/99593160-da687e80-29b6-11eb-98dc-24ec012e802b.png)

2020-11-18 22:05 UTC, zarathustra323 requested changes
Out of the gate this functionality needs to be configurable, or implement fallback logic to hide these features when campaigns are not found / empty. 

This is because email campaigns only work with Omeda, and not all Base customers use Omeda, which would present in confusing results to users that aren't using Omeda (or, are using Omeda, but aren't deploying through Base).

Historically, we used email schedules to display possible deployment dates, not email campaigns

2020-11-20 14:37 UTC, B77Mills commented
@zarathustra323  both the route and the admin implement checks for null campaigns and that there is at least one campaign returned.  

In the route if campaigns is null and `?date=latest` it will return the same error as if the date formate was wrong and displays the invalid date error.  

In the admin it will display deployments with only show the Today and Calendar links as shown in the screen capture.  

I can also add a check for a config value in the map-campaigns.js file if need be.  This might also add the ability to further configure how to retrieve these ini the future, but at the moment I don't know of any other examples of campaign implementations or where they would be stored, IE mailChimp.

2020-11-30 13:05 UTC, B77Mills commented
@zarathustra323  Just wanted to check on this one and see if you would have some time to review this today?  Let me know if you have any questions.

2020-11-30 17:15 UTC, zarathustra323 approved these changes

2020-11-30 17:15 UTC, merged